apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-api
  name: auth-api
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: alorin/auth-api:0.0.3
        resources:
          requests:
            cpu: "128m"
        ports:
        - containerPort: 4001
          protocol: TCP
        - containerPort: 4000
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 4001
            path: /user
        volumeMounts:
        - mountPath: /proto/user/v1alpha
          name: proto
      volumes:
      - name: proto
        configMap:
          name: proto-file
      terminationGracePeriodSeconds: 60
  minReadySeconds: 60