apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
spec:
  type: NodePort
  selector:
    app: auth-api
  ports:
  - port: 4000
    name: auth-api
    protocol: TCP
    targetPort: 4000
  - port: 4001
    name: http
    protocol: TCP
    targetPort: 4001